
/*
read boundaries of California counties and citys downloaded from osm-boundaries
and figure out which cities are in which counties

read intersection files generated by gpsaddr from ./temp/input/  
write the new files to temp/output/

*/

'use strict';
import { count } from 'console';
import fs from 'fs';
import turf from '@turf/turf';

import { pointToPolygonDistance } from "@turf/point-to-polygon-distance";
import { pointOnFeature } from "@turf/point-on-feature";


import { exit } from 'process';

//const result = turf.pointsWithinPolygon();

for (let j = 0; j < process.argv.length; j++) {
	console.log(j + ' -> ' + (process.argv[j]));
}

const osmboundaryFile = './data/osm-boundaries/CaliforniaAndCountiesAndCities.geojson';


//'intersections_oakland.json'.match(/intersections_(.*).json/)
//Array [ "intersections_oakland.json", "oakland" ]

/* utility functions */

function getFilesFromDirectory(dirName, regex) {
	const files = fs.readdirSync(dirName);
	const retval = [];
	for (const f of files) {
		if (!regex || f.match(regex)) {
			retval.push(f);
		}
	}
	return retval;
}


var lastTime = 0;
function getMS(msg) {
	const thisTime = Date.now();
	const diff = thisTime - lastTime;
	lastTime = thisTime;

	if (msg) {
		console.log(msg, ':', diff, ' ms')
	}
	return diff;
}

function dumpSet(name, set) {
	console.log("Set: ", name);
	for (const e of set) {
		console.log(e);
	}
}

function getJson(filename) {
	const str = fs.readFileSync(filename).toString();
	const obj = JSON.parse(str);
	return obj;
}

// write out fixed file
function writeJson(file, obj) {
	const str = JSON.stringify(obj, null, 2);

	fs.writeFileSync(file, str);
}

function truncateFloat(f, fractionDigits) {
	return parseFloat(f.toFixed(fractionDigits))
}

//const mapStreetPairToGPS = new Map();
function makeKey(s1, s2) {
	const key = s1.toUpperCase().trim() + '/' + s2.toUpperCase().trim();
	return key;
}



console.log("Loading boundary data from", osmboundaryFile);
const boundaryJSON = getJson(osmboundaryFile);

// put all the counties and sf in a map


function makeTurfFromFeature(geometry) {

	//var pt = turf.point([-122.2788, 37.847100]);

	var feature = turf.feature(geometry);
	feature.bbox = turf.bbox(feature);



	//const bInside = turf.inside(pt, feature);

	//	if (bInside) {
	//	console.log("Contains Berkeley");
	//}

	return feature;
}
const mapCountyToBoundary = new Map(); // county name => turf feature for county border
const mapCountyToCities = new Map(); // county name => Set of city names
const mapCityToBoundary = new Map();  // city name => turf feature of city border

for (const b of boundaryJSON.features) {
	const name = b.properties.name;
// SF has only 1 bdry in osm-boundaries. it is both the city and county bdry admin level 6
	if (name.includes("County") || name == 'San Francisco') {
		//console.log( "Found county ", name)

		const turfFeature = makeTurfFromFeature(b.geometry)
		mapCountyToBoundary.set(name, turfFeature);
		mapCountyToCities.set(name, new Set());
	}
}

for (const b of boundaryJSON.features) {
	const name = b.properties.name;

	if (name == 'San Francisco') {
		console.log(name);
	}

	if (!name.includes("County") /*&& name != 'San Francisco'*/ && name != 'California') {
		console.log( "Found city ", name)
		const cityFeature = makeTurfFromFeature(b.geometry);


	//	var center = turf.centerOfMass(cityFeature);
	var center = pointOnFeature( cityFeature);
		var found = false
		for (const [k, v] of mapCountyToBoundary.entries()) {

			if (k=='San Francisco') {
				console.log("found sf county");
			}

			const bInside = turf.inside(center, v);

			if (bInside) {
				//	console.log('',k,'contains',name);
				mapCityToBoundary.set(name, cityFeature);
				found = true
				const s = mapCountyToCities.get(k);
				s.add(name);
			}
		}
		if (!found) {
			console.log("no county found for", name)
		}

	}
}

class CountyCities {
	countyName; // string
	cityNames; // array of strings
}

const countyArray = [];
const arrKeys = Array.from(mapCountyToCities.keys()).sort();

var countyCode = 1;

for (const k of arrKeys) {

	const v = mapCountyToCities.get(k)
	const obj = new CountyCities;
	obj.countCode = countyCode++;
	obj.countyName = k;
	
	obj.cityNames = Array.from(mapCountyToCities.get(k)).sort();
	
	countyArray.push(obj)
}

countyArray.sort();

// write to file

writeJson('./data/county_cities.json', countyArray);

/*
{
 "type": "FeatureCollection",
 "features": [
  {
   "type": "Feature",
   "geometry": {
	"type": "Point",
	"coordinates": [
	 -122.2931254,
	 37.7849613
	]
   },
   "properties": {
	"streets": [
	 "Barbers Point Road",
	 "West Midway Avenue"
	]
   }
  },
  */






function addCityCountyToIntersectionGeoJson(f, countyName, countyBorder, mapCityBorders) {

	const ptInter = turf.point(f.geometry.coordinates);

	const bInCounty = turf.inside(ptInter, countyBorder);
	if (bInCounty) {
		f.properties.County = countyName;
	} else {
		const dist = pointToPolygonDistance(ptInter, countyBorder, { units: 'meters' })  // kilometers, miles, meters
		console.log('County', countyName, 'does not contain', f.properties.streets, dist)

		return
	}

	for (const [k, v] of mapCityBorders.entries()) {
		const bInside = turf.inside(ptInter, v);
		if (bInside) {
			f.properties.City = k;
			break;
		}
	}
	if (!f.properties.City) {
		f.properties.City = 'Unincorporated'
	}
}

const thisCounty = 'Alameda County';
function fileNameIze(str) {
	return str.replaceAll(' ', '_');

}
function fixIntersections(thisCounty) {
	const borderCounty = mapCountyToBoundary.get(thisCounty);
	const borderCities = new Map();

	for (const cityName of mapCountyToCities.get(thisCounty)) {
		borderCities.set(cityName, mapCityToBoundary.get(cityName))
	}
	const intersectionJson = getJson('./temp/input/intersections_' + fileNameIze(thisCounty) + '.json');

	for (const f of intersectionJson.features) {
		addCityCountyToIntersectionGeoJson(f, thisCounty, borderCounty, borderCities);
	}

	writeJson('./temp/output/intersections_' + fileNameIze(thisCounty) + '.json', intersectionJson);
}

//fixIntersections('San Luis Obispo County')

for (const obj of countyArray) {
	console.log("fixing county ", obj.countyName);
	fixIntersections(obj.countyName)
}
/*
const borderAlamedaCounty = mapCountyToBoundary.get(thisCounty);
const borderCities = new Map();

for (const cityName of mapCountyToCities.get(thisCounty)) {
	borderCities.set(cityName, mapCityToBoundary.get(cityName))
}
const testIntersJson = getJson('./data/intersection/hide/intersections_alamedacounty.json');

for (const f of testIntersJson.features) {
	addCityCountyToIntersectionGeoJson(f, 'Alameda County', borderAlamedaCounty, borderCities);
}

writeJson('testaddcitytointers.json', testIntersJson)
*/

console.log("bye");